---
  - name: Update apt cache
    become: yes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade packages
    become: yes
    apt: upgrade=dist force_apt_get=yes

  - name: Install packages
    apt:
      pkg:
        - build-essential
        - software-properties-common
        - gcc
        - python3-dev 
        - python3-setuptools 
        - python3-pip 
        - wireguard
      state: latest

  - name: Creates directory
    file: path=/root/{{project}} state=directory

  - name: Install Flask Framework
    pip:
      name: flask
      virtualenv: "{{project_name_path}}venv"
      virtualenv_command: virtualenv
      virtualenv_python: python3

  - name: Pip install requirements
    pip:
      requirements: "{{project_name_path}}requirements.txt"
      virtualenv: "{{project_name_path}}venv"
      virtualenv_python: python3

  - name: Create config
    template: src=tunnel.service dest=/etc/systemd/system/tunel.service

  - name: Systemd restart
    tasks:
    - name: Restar service 
      become: true
      systemd: 
        name: tunel
        state: restarted